orbs:
  node: circleci/node@1.1
version: 2.1

jobs:
  deploy:
    executor:
      name: node/default
      tag: '13.1.0'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: npm i netlify-cli
      - run: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --message "Deploy via Circle CI."

workflows:
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
