orbs:
  node: circleci/node@1.1
version: 2.1

jobs:
  build:
    executor:
      name: node/default
      tag: '13.1.0'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - netlify.toml
  deploy:
    executor:
      name: node/default
      tag: '13.1.0'
    working_directory: ~/site
    steps:
      - attach_workspace:
          at: ~/site
      - run: npm i netlify-cli
      - run: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --message "Deploy via Circle CI."

workflows:
  main:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
