orbs:
  node: circleci/node@1.1
version: 2.1

jobs:
  deploy:
    executor:
      name: node/default
      tag: '13.1.0'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn build

workflows:
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
